### PR TITLE
Nsf core fw impl

### PR DESCRIPTION
**Pull request by mak-454**
@mageshgv-oc @chandra-k @njagadish @hemanthravi

### CODE REVIEW

**Comment by mageshgv-oc** [comment]
Ahmed, Can you remove the DB code from this PR and only create a PR with Framework changes.

It will be easier to review these independently.

**Comment by mageshgv-oc** [comment]
@mak-454

**Comment by mageshgv-oc** [comment]
@songole @ashutosh-mishra @Vikash082 @maheshkurund @rajendramachani

**Comment by mak-454** [comment]
Closing this pull request as there is some conflict.. created a new branch and will raise pull request for that.

**Pull request closed without merging**
